sudo: required

language: cpp

os:
  - linux

notifications:
  - email: false

services:
  - docker

env:
  - DOCKER_IMAGE=batk/bat-testenv:centos7-root6
  - DOCKER_IMAGE=batk/bat-testenv:centos7-root5

before_install:
  - docker pull "$DOCKER_IMAGE"
  - export DOCKER_INSTANCE=`docker run -it -d "$DOCKER_IMAGE" /bin/bash`
  - docker cp . "$DOCKER_INSTANCE:/root/bat"

script:
  - docker exec "$DOCKER_INSTANCE" /bin/sh -c "cd /root/bat && tools/test-bat.sh"
  # save the docs for deployment
  - mkdir -p /tmp/master/ref-guide
  - mkdir -p /tmp/master/manual
  - docker cp "$DOCKER_INSTANCE":/root/bat/doc/ref-guide/html/ /tmp/master/ref-guide/
  - docker cp "$DOCKER_INSTANCE":/root/bat/doc/manual/BAT-manual.pdf /tmp/master/manual/
  - docker cp "$DOCKER_INSTANCE":/root/bat/doc/manual/html/ /tmp/master/manual/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: manual
  repo: fredRos/bat-docs
  verbose: true
  local-dir: /tmp/master
