sudo: required

language: cpp

os:
  - linux

notifications:
  - email: false

services:
  - docker

env:
  - DOCKER_IMAGE=batk/bat-testenv:centos7-root6

before_install:
  - docker pull "$DOCKER_IMAGE"
  - export DOCKER_INSTANCE=`docker run -it -d "$DOCKER_IMAGE" /bin/bash`
  - docker cp . "$DOCKER_INSTANCE:/root/bat"

script:
  - docker exec "$DOCKER_INSTANCE" /bin/sh -c "cd /root/bat && tools/test-bat.sh"
